FROM golang:alpine as builder
RUN apk add make git

ARG version=v0.8.0
RUN \
    git clone https://github.com/poseidon/matchbox/ \
        --branch $version \
        --depth 1 && \
    cd matchbox && \
    make build && \
    mv bin/matchbox /bin && \
    cd .. && rm -Rf matchbox

# ---
FROM alpine:3.10 as final
COPY --from=builder bin/matchbox /bin/matchbox
EXPOSE 8080

ENTRYPOINT ["/bin/matchbox"]
