---
version: "3.4"
x-dnsmasq-base: &dnsmasq_base
  build:
    dockerfile: Dockerfile.dnsmasq
    context: .
  entrypoint:
    - dnsmasq
    - --log-facility=-
    - --keep-in-foreground
    - --user=root

    # disable DNS (port 53)
    - --port=0
  restart: unless-stopped

services:
  matchbox:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.matchbox
      context: .
    volumes:
      - ./matchbox:/tmp/matchbox:ro
      - ./docker-entrypoint.sh:/bin/entrypoint.sh:ro
      - ./docker-entrypoint.d:/docker-entrypoint.d:ro
    environment:
      MATCHBOX_LOG_LEVEL: debug
      MATCHBOX_ADDRESS: 0.0.0.0:8080
    entrypoint: /bin/entrypoint.sh
    command: /bin/matchbox
    env_file: matchbox.env
    ports:
      - 8080:8080

  dhcpd:
    <<: *dnsmasq_base
    # todo: use dhcp relay
    network_mode: host
    command:
      - --log-queries
      - --log-dhcp

      # Act as ProxyDHCP server
      # only respond to PXE requests coming from same subnet as the given IP
      - --dhcp-range=192.168.1.0,proxy


      # Add tag for Raspberry Pi if beginning of DHCP option 97 (UUID/GUID) matches known values for raspi bootloader (`RPi` in ASCII)
      - --dhcp-match=set:raspi-bootloader,option:client-machine-id,00:52:50
      # Raspberry Pi bootloader identifies as PC BIOS client system type (CSA) and requires a specific DHCP Offer (DHCP option 43) with the following text
      - --pxe-service=tag:raspi-bootloader,x86PC,Raspberry Pi Boot
      # Raspberry Pi bootloader downloads config.txt and loads file configured as `kernel`, generally U-Boot


      # U-Boot PXE client identifies as ARM64_EFI client system type (CSA)
      - --dhcp-match=set:arm64_efi,option:client-arch,11
      # U-Boot PXE client (`bootcmd_dhcp`) reads filename from DHCP option 67 (bootfile)
      - --dhcp-boot=tag:arm64_efi,ipxe/ipxe.arm64.efi

      # if DHCP userclass is iPXE, add ipxe tag
      - --dhcp-userclass=set:ipxe,iPXE
      # TODO replace templated ${server} value with `0.0.0.0` which dnsmasq renders to the current IP address of dnsmasq
      - --dhcp-boot=tag:ipxe,http://${server}:8080/assets/introspect.ipxe

      # TODO investigate why --dhcp-option-force doesn't work with proxyDHCP
      # DHCP option 66 (Server-Name) is only populated for dnsmasq pxe-services
      # TODO consolidate to single dhcp-boot entry when host can be parsed from DHCP filename (URL), or manually set DHCP option 66
    cap_add:
      - NET_ADMIN

  tftpd:
    <<: *dnsmasq_base
    command:
      - --enable-tftp
      - --tftp-root=/var/lib/tftpboot
    ports:
      - "69:69/udp"

    # TODO build universal (not machine-specific) tftp files into docker image
    # https://github.com/pftf/RPi4/issues/59
