# docker continuous delivery
# deliver docker images to configured repo with tags to match branches and git tags
---
name: Build & Deliver
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.dnsmasq
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          # TODO use docker/metadata-action to tag via `type=ref`
          tags: |
            ghcr.io/ivan-c/dnsmasq-pxe:latest
